[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["rm -rf node_modules/.cache || true", "npm ci --cache /tmp/.npm"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx serve -s build -l $PORT --single"
